a = [
		"Redes de Computadores",
		"Din\u00e2mica Orbital",
		"Engenharia de Tecidos",
		"An\u00e1lise no Rn II",
		"Qualidade em Sistemas",
		"Sistemas de Controle II",
		"Bioquimica Experimental",
		"Seguran\u00e7a em Redes",
		"Teorias da Justi\u00e7a",
		"Gen\u00e9tica Molecular",
		"Seguran\u00e7a de Dados",
		"Sensores e Transdutores",
		"Pensamento Cr\u00edtico",
		"L\u00f3gica B\u00e1sica",
		"Geometria Diferencial I",
		"Desempenho de Aeronaves",
		"Seguran\u00e7a de Redes",
		"Bases Matem\u00e1ticas",
		"Qu\u00edmica Ambiental",
		"Metalurgia F\u00edsica",
		"Sinais Aleat\u00f3rios",
		"Engenharia Unificada I",
		"Sistemas de Controle I",
		"M\u00e1quinas de Fluxo",
		"Economia Monet\u00e1ria",
		"Ger\u00eancia de Ativos",
		"Microbiologia Ambiental",
		"Filosofia Pol\u00edtica",
		"Psicologia Experimental",
		"Pol\u00edticas Culturais",
		"Fundamentos de Geometria",
		"Sistemas Multim\u00eddia",
		"\u00c9tica e Justi\u00e7a",
		"Grupos de Lie e Simetrias",
		"Sistemas Microprocessados",
		"Conhecimento e \u00c9tica",
		"Materiais Comp\u00f3sitos",
		"Morfofisiologia Evolutiva",
		"F\u00edsica T\u00e9rmica",
		"Controle N\u00e3o-Linear",
		"Geometria Anal\u00edtica",
		"Geologia e Paleontologia",
		"Matem\u00e1tica Discreta",
		"Economia e Meio Ambiente",
		"Materiais Cer\u00e2micos",
		"Circuitos El\u00e9tricos I",
		"Res\u00edduos S\u00f3lidos",
		"Materiais Polim\u00e9ricos",
		"Hist\u00f3ria do Urbanismo",
		"An\u00e1lise de Algoritmos",
		"Qu\u00edmica dos Elementos",
		"Qu\u00edmica dos Materiais",
		"Sistemas Biol\u00f3gicos II",
		"Circuitos El\u00e9tricos II",
		"Comunica\u00e7\u00e3o e Redes",
		"Citogen\u00e9tica B\u00e1sica",
		"Semin\u00e1rios em Biologia I",
		"Interface Humano-M\u00e1quina",
		"Fen\u00f4menos Mec\u00e2nicos",
		"Sistemas Fluidomec\u00e2nicos",
		"Desenvolvimento e Aprendizagem",
		"Neurobiologia do Comportamento",
		"Oficina de Planejamento Urbano",
		"Mec\u00e2nica Anal\u00edtica I",
		"Sociologia dos Territ\u00f3rios",
		"Teoria de Grupos em F\u00edsica",
		"Mec\u00e2nica Anal\u00edtica II",
		"Cartografia e Geoprocessamento",
		"Sele\u00e7\u00e3o de Materiais",
		"Clima e Cultura Organizacional",
		"Sustentabilidade e Indicadores",
		"Programa\u00e7\u00e3o Paralela",
		"Propaga\u00e7\u00e3o e Antenas",
		"Extens\u00f5es Alg\u00e9bricas",
		"S\u00edntese de Pol\u00edmeros",
		"Semin\u00e1rios em Biologia II",
		"Temas e Problemas em Filosofia",
		"Termodin\u00e2mica Aplicada II",
		"Mec\u00e2nica dos S\u00f3lidos",
		"Log\u00edstica e Meio Ambiente",
		"Programa\u00e7\u00e3o para Web",
		"Teoria Cl\u00e1ssica dos Campos",
		"Efici\u00eancia Energ\u00e9tica",
		"Filosofia da Educa\u00e7\u00e3o",
		"Sistem\u00e1tica e Biogeografia",
		"Ci\u00eancias Atmosf\u00e9ricas",
		"Fundamentos de Desenho e Projeto",
		"Processamento Digital de Imagens",
		"Sistemas de Informa\u00e7\u00e3o",
		"Quest\u00f5es Ambientais Globais",
		"Ensino de Morfofisiologia Humana",
		"Ecologia do Ambiente Antropizado",
		"Tecnologia da Informa\u00e7\u00e3o",
		"Paradigmas de Programa\u00e7\u00e3o",
		"Instrumenta\u00e7\u00e3o e Controle",
		"\u00c1lgebra Linear Avan\u00e7ada I",
		"Din\u00e2mica N\u00e3o-Linear e Caos",
		"Princ\u00edpios de Termodin\u00e2mica",
		"Equipamentos M\u00e9dico-Hospitalares",
		"Patologias do Sistema Nervoso Central",
		"Pr\u00e1tica de Ensino de Filosofia V",
		"Pr\u00e1tica de Ensino de Filosofia II",
		"Processamento da Informa\u00e7\u00e3o",
		"Comunica\u00e7\u00f5es Multim\u00eddia",
		"Instala\u00e7\u00f5es El\u00e9tricas I",
		"L\u00f3gica em Sistemas de Gest\u00e3o",
		"Pr\u00e1ticas de Ensino de Biologia II",
		"Din\u00e2mica de Fluidos Computacional",
		"Transforma\u00e7\u00f5es Qu\u00edmicas",
		"Energia: Origens, Convers\u00e3o e Uso",
		"Neuromec\u00e2nica do Movimento Humano",
		"Transfer\u00eancia de Calor Industrial",
		"Hist\u00f3ria da Cidade e do Urbanismo",
		"Qu\u00edmica Org\u00e2nica Experimental",
		"Mec\u00e2nica dos Fluidos Avan\u00e7ada",
		"Sistemas de Abastecimento de \u00c1guas",
		"M\u00e9todos Experimentais em Engenharia",
		"Pr\u00e1ticas de Ensino de F\u00edsica I",
		"Instala\u00e7\u00f5es El\u00e9tricas II",
		"Fundamentos de Geologia para Engenharia",
		"Turbinas T\u00e9rmicas de Pot\u00eancia",
		"Bases Biol\u00f3gicas para Engenharia II",
		"Economia Brasileira Contempor\u00e2nea I",
		"Pr\u00e1ticas de Ensino de Qu\u00edmica I",
		"Introdu\u00e7\u00e3o \u00e0 Biotecnologia",
		"Hist\u00f3ria do Pensamento Econ\u00f4mico",
		"Escoamento Multif\u00e1sico de Petr\u00f3leo",
		"T\u00f3picos Avan\u00e7ados em Macroeconomia",
		"Meio Ambiente e Pol\u00edticas P\u00fablicas",
		"Fun\u00e7\u00f5es de Vari\u00e1veis Complexas",
		"Computa\u00e7\u00e3o Evolutiva e Conexionista",
		"Avalia\u00e7\u00e3o no Ensino de Qu\u00edmica",
		"Oficina de Planejamento Macro e Meso Regional",
		"Base Experimental das Ci\u00eancias Naturais",
		"Viol\u00eancia e Seguran\u00e7a P\u00fablica",
		"Cer\u00e2micas Especiais e Refrat\u00e1rias",
		"Sistemas de Gerenciamento de Banco de Dados",
		"Forma\u00e7\u00e3o do Sistema Internacional",
		"Programa\u00e7\u00e3o de Software Embarcado",
		"Engenharia de Combust\u00edveis F\u00f3sseis",
		"Qu\u00edmica Anal\u00edtica Cl\u00e1ssica II",
		"Pr\u00e1ticas em Ci\u00eancias e Humanidades",
		"Origem da Vida e Diversidade dos Seres Vivos",
		"Pr\u00e1ticas de Ensino de Matem\u00e1tica I",
		"Princ\u00edpios de An\u00e1lise Qu\u00edmica",
		"Tempos, M\u00e9todos e Arranjos F\u00edsicos",
		"Projeto de Sistemas de Comunica\u00e7\u00e3o",
		"Finan\u00e7as I (Apre\u00e7amento de Ativos)",
		"Semin\u00e1rios em Materiais Avan\u00e7ados",
		"Forma\u00e7\u00e3o Econ\u00f4mica do Brasil",
		"Fundamentos de M\u00e1quinas El\u00e9tricas",
		"Aplica\u00e7\u00f5es de Microcontroladores",
		"Avalia\u00e7\u00e3o de Desempenho de Redes",
		"Pr\u00e1ticas de Ensino de F\u00edsica III",
		"Sistemas e Processos de Produ\u00e7\u00e3o",
		"Economia Brasileira Contempor\u00e2nea III",
		"Teoria Aritm\u00e9tica dos N\u00fameros II",
		"Tecnologia de Produ\u00e7\u00e3o de Etanol",
		"Energia de Sistemas Solares T\u00e9rmicos",
		"Economia Brasileira Contempor\u00e2nea II",
		"Programa\u00e7\u00e3o Orientada a Objetos",
		"Fundamentos de M\u00e1quinas T\u00e9rmicas",
		"Pr\u00e1ticas de Ensino de Qu\u00edmica II",
		"Pr\u00e1ticas de Ensino de F\u00edsica II",
		"Desenvolvimento S\u00f3cio-Econ\u00f4mico",
		"Princ\u00edpios de Comunica\u00e7\u00e3o",
		"Caracteriza\u00e7\u00e3o de Biomateriais",
		"Introdu\u00e7\u00e3o \u00e0s Engenharias",
		"Teoria Aritm\u00e9tica dos N\u00fameros",
		"T\u00f3picos Experimentais em Materiais",
		"Pr\u00e1ticas de Ensino de Biologia III",
		"Instrumenta\u00e7\u00e3o Biom\u00e9dica",
		"Gest\u00e3o Ambiental na Ind\u00fastria",
		"Pr\u00e1tica de Ensino de Filosofia III",
		"Princ\u00edpios de Imagens M\u00e9dicas",
		"Equa\u00e7\u00f5es Diferenciais Parciais",
		"Qu\u00edmica Anal\u00edtica Instrumental",
		"Vida Artificial na Computa\u00e7\u00e3o",
		"An\u00e1lise Econ\u00f4mica de Projetos",
		"Bases Biol\u00f3gicas para Engenharia I",
		"Laborat\u00f3rio de Bioinform\u00e1tica",
		"Pr\u00e1tica de Ensino de Filosofia IV",
		"Ondas Eletromagn\u00e9ticas Aplicadas",
		"Programa\u00e7\u00e3o Matem\u00e1tica",
		"Pr\u00e1ticas de Ensino de Biologia I",
		"Modelagem de Sistemas Biol\u00f3gicos",
		"Planejamento e Pol\u00edtica Regional",
		"Engenharia de Biocombust\u00edveis II",
		"Sistemas de Esgotos e Drenagem Urbana",
		"Inova\u00e7\u00e3o Tecnol\u00f3gica",
		"Economia, Sociedade e Meio Ambiente",
		"Mat\u00e9rias Primas Cer\u00e2micas",
		"Planejamento e Controle de Projetos",
		"Projeto de Sistemas Multim\u00eddia",
		"Qu\u00edmica Org\u00e2nica Aplicada",
		"Manufatura Integrada por Computador",
		"Comunica\u00e7\u00f5es \u00d3pticas",
		"Estado e Sociedade Civil Organizada",
		"Laborat\u00f3rio de Calor e Fluidos",
		"Subesta\u00e7\u00e3o e Equipamentos",
		"Controle Robusto Multivari\u00e1vel",
		"Linguagens Formais e Aut\u00f4mata",
		"Sociedade Civil Organizada Global",
		"Organiza\u00e7\u00e3o do Trabalho",
		"Comunica\u00e7\u00f5es M\u00f3veis",
		"Qualidade da Energia El\u00e9trica",
		"Estrutura At\u00f4mica e Molecular",
		"Algoritmos e Estruturas de Dados I",
		"Hist\u00f3ria da Matem\u00e1tica",
		"Liga\u00e7\u00f5es Qu\u00edmicas",
		"Materiais para Energia e Ambiente",
		"Economia de Reatores Nucleares",
		"F\u00edsica de Semicondutores",
		"Comunica\u00e7\u00e3o Digital",
		"Sequ\u00eancias e S\u00e9ries",
		"Mec\u00e2nica Qu\u00e2ntica",
		"Pol\u00edtica Metropolitana",
		"Arquitetura de Computadores",
		"Gest\u00e3o Urbano-Ambiental",
		"Bases Conceituais da Energia",
		"Processos Estoc\u00e1sticos",
		"Rea\u00e7\u00f5es Nucleares",
		"Mec\u00e2nica Cl\u00e1ssica",
		"Finan\u00e7as P\u00fablicas",
		"Territ\u00f3rio e Sociedade",
		"Re\u00faso de \u00c1gua",
		"Geometria Diferencial II",
		"Economia Internacional I",
		"Economia Institucional I",
		"Gen\u00e9tica Geral",
		"Optoeletr\u00f4nica",
		"Biomas Brasileiros",
		"Banco de Dados",
		"Bio\u00e9tica",
		"Fot\u00f4nica",
		"Imunologia",
		"Custos",          // pois é! tem uma disciplina de nome "Custos" e outra de nome "Grupos"
		"Grupos",          // fiquei curioso pra saber do que se trata.
		"Reologia",
		"LIBRAS",
		"Demografia",
		"Geotecnia",
		"Ergonomia",
		"Hidrologia",
		"TV Digital",
		"Reologia I",
		"Climatologia",
		"Metodologia",
		"Toxicologia",
		"\u00d3ptica",
		"\u00c9tica",
		"Clima Urbano",
		"Virologia",
		"Ceticismo",
		"Neuroarte",
		"M\u00f3dulos",
		"Astrobiologia",
		"Parasitologia",
		"Probabilidade",
		"Redes sem Fio",
		"Econometria I",
		"Est\u00e9tica",
		"Biomateriais",
		"Avi\u00f4nica",
		"Topologia II",
		"Topologia I",
		"Pragmatismo",
		"Farmacologia",
		"Compiladores",
		"Neuroanatomia",
		"Did\u00e1tica",
		"Espectroscopia",
		"Hidr\u00e1ulica",
		"Placas e Cascas",
		"Teoria das Filas",
		"Etnofarmacologia",
		"Sistemas CAD/CAM",
		"Combust\u00e3o I",
		"Empreendedorismo",
		"Teoria dos Jogos",
		"Ecologia vegetal",
		"Macroeconomia II",
		"Ecologia Animal",
		"Econometria III",
		"Din\u00e2mica I",
		"Biof\u00edsica",
		"Macroeconomia I",
		"Economia Urbana",
		"Existencialismo",
		"Microbiologia I",
		"Gen\u00e9tica I",
		"Microeconomia I",
		"Din\u00e2mica II",
		"Aeroelasticidade",
		"Ecologia Vegetal",
		"Petrof\u00edsica",
		"Biologia Celular",
		"Projeto Dirigido",
		"Econometria II",
		"Microeconomia II",
		"Diagramas de Fase",
		"Termoqu\u00edmica",
		"Sistemas Digitais",
		"Conflitos Sociais",
		"Engenharia Humana",
		"Vibra\u00e7\u00f5es",
		"Estado S\u00f3lido",
		"Uso do Solo Urbano",
		"Biosseguran\u00e7a",
		"Controle Discreto",
		"Biologia Animal I",
		"Teoria dos Grafos",
		"Evolu\u00e7\u00e3o",
		"Psicofarmacologia",
		"Macroeconomia III",
		"Biologia Vegetal I",
		"Engenharia Laboral",
		"Circuitos Digitais",
		"Filosofia da Mente",
		"Filtragem Adaptativa",
		"Engenharia de Metais",
		"Pol\u00edtica Urbana",
		"Sa\u00fade Ambiental",
		"Pesquisa Operacional",
		"An\u00e1lise Real II",
		"Sistemas Multiagentes",
		"Reciclagem e Ambiente",
		"Engenharia de Software",
		"Recursos H\u00eddricos",
		"Acumuladores de Energia",
		"Engenharia Unificada II",
		"Fundamentos de Geologia",
		"Filosofia da L\u00f3gica",
		"Engenharia de Filmes Finos",
		"Sistemas de Pot\u00eancia I",
		"Fundamentos de \u00c1lgebra",
		"Termodin\u00e2mica Aplicada",
		"Vibra\u00e7\u00f5es Lineares",
		"Intelig\u00eancia Artificial",
		"Programa\u00e7\u00e3o Segura",
		"Antropologia Filos\u00f3fica",
		"Evolu\u00e7\u00e3o Molecular",
		"Escoamento Compress\u00edvel",
		"Minera\u00e7\u00e3o de Dados",
		"Sistemas de Propuls\u00e3o I",
		"F\u00edsica do Cont\u00ednuo",
		"Bot\u00e2nica Econ\u00f4mica",
		"Engenharia de Cer\u00e2micas",
		"Bases Neurais da Motricidade",
		"Sistemas Biol\u00f3gicos III",
		"M\u00e9todos de Planejamento",
		"Educa\u00e7\u00e3o Ambiental",
		"Sistemas de Pot\u00eancia II",
		"Fundamentos de Rob\u00f3tica",
		"Transfer\u00eancia de Calor I",
		"Materiais e Suas Propriedades",
		"Teoria de Controle \u00d3timo",
		"Mec\u00e2nica Cl\u00e1ssica I",
		"Dispositivos Eletr\u00f4nicos",
		"C\u00e1lculo de Probabilidade",
		"Pesquisa Operacional Aplicada",
		"Qu\u00edmica do Petr\u00f3leo",
		"Bioqu\u00edmica Experimental",
		"Fen\u00f4menos de Transporte",
		"Pol\u00edticas de sa\u00fade",
		"Mec\u00e2nica dos Fluidos II",
		"Tecnologia da Combust\u00e3o",
		"Lasers e \u00d3ptica Moderna",
		"L\u00f3gica Program\u00e1vel",
		"M\u00e1quinas El\u00e9tricas",
		"Regimes e Formas de Governo",
		"Inform\u00e1tica Industrial",
		"Biologia do Desenvolvimento",
		"Propuls\u00e3o Aeroespacial",
		"Mec\u00e2nica dos Fluidos I",
		"Teoria Eletromagn\u00e9tica",
		"Estudos \u00c9tnico-Raciais",
		"Processamento de V\u00eddeo",
		"Pol\u00edticas Educacionais",
		"Acionamentos El\u00e9tricos",
		"Fundamentos de An\u00e1lise",
		"Sistemas Biol\u00f3gicos IV",
		"M\u00e1quinas T\u00e9rmicas",
		"Hist\u00f3ria da Astronomia",
		"Economia do Territ\u00f3rio",
		"Aprendizado de M\u00e1quina",
		"Transfer\u00eancia de Massa",
		"Microscopia Eletr\u00f4nica",
		"Mem\u00f3ria e Aprendizagem",
		"Projeto de Filtros Digitais",
		"Finan\u00e7as Corporativas",
		"Sistemas Distribu\u00eddos",
		"Temas da Filosofia Moderna",
		"Fundamentos de Imunologia",
		"Sistemas Biol\u00f3gicos I",
		"C\u00e1lculo Num\u00e9rico",
		"Ci\u00eancia dos Materiais",
		"Economia Institucional II",
		"M\u00e9todos Variacionais",
		"T\u00e9cnicas em Pesquisa",
		"Engenharia Econ\u00f4mica",
		"Contabilidade B\u00e1sica",
		"Economia Internacional II",
		"Estrutura da Mat\u00e9ria",
		"Oficina de Projeto Urbano",
		"Mercado Imobili\u00e1rio",
		"Redes de Alta Velocidade",
		"F\u00edsica Qu\u00e2ntica",
		"Pr\u00e1ticas de Ecologia",
		"Engenharia Log\u00edstica",
		"Engenharia Cl\u00ednica I",
		"Temas da Filosofia Antiga",
		"Temas Contempor\u00e2neos",
		"Laborat\u00f3rio de Redes",
		"F\u00edsica Computacional",
		"Eletr\u00f4nica Aplicada",
		"Morfofisiologia Humana I",
		"Teoria das Decis\u00f5es",
		"Projeto de Aeronaves I",
		"Zoologia de Vertebrados",
		"Sistemas de Micro-ondas",
		"Filosofia da Linguagem",
		"Sistemas T\u00e9rmicos",
		"Sistemas de Microondas",
		"Fluidos Qu\u00e2nticos",
		"Aeron\u00e1utica II",
		"\u00c1lgebra Linear",
		"Web Sem\u00e2ntica",
		"Biologia Animal II",
		"An\u00e1lise Real I",
		"Nanocomp\u00f3sitos",
		"Economia Industrial",
		"Biologia Vegetal III",
		"Psicologia Cognitiva",
		"Eletromagnetismo III",
		"Economia do Trabalho",
		"Economia de Empresas",
		"An\u00e1lise no Rn I",
		"Projetos Industriais",
		"Qu\u00edmica Forense",
		"Biologia Animal III",
		"Aerodin\u00e2mica I",
		"Economia da Energia",
		"Biologia Vegetal II",
		"Ergonomia Cognitiva",
		"Bioestat\u00edstica",
		"An\u00e9is e Corpos",
		"Tecnologias Sociais",
		"Mec\u00e2nica Geral",
		"Aerodin\u00e2mica II",
		"Identidade e Cultura",
		"Saneamento Ambiental",
		"Aeron\u00e1utica I",
		"Sensoriamento Remoto",
		"Sistemas Inteligentes",
		"Sistemas Operacionais",
		"Design de Dispositivos",
		"Projeto de Aeronaves I",
		"Teoria da Relatividade",
		"Teoria da Elasticidade",
		"Pol\u00edticas Sociais",
		"Telefonia Fixa Moderna",
		"Geografia Pol\u00edtica",
		"Propriedade Intelectual",
		"Eletr\u00f4nica Digital",
		"Res\u00edduos Nucleares",
		"Geomorfologia Descritiva",
		"Sistemas de Controle III",
		"Materiais Met\u00e1licos",
		"Pensamento Econ\u00f4mico",
		"Bioqu\u00edmica Funcional",
		"Materiais Nanoestruturados",
		"Fun\u00e7\u00f5es Especiais",
		"Estudos do Meio F\u00edsico",
		"Transportes e Meio Ambiente",
		"Temas da Filosofia Medieval",
		"Fen\u00f4menos T\u00e9rmicos",
		"Engenharia de Pol\u00edmeros",
		"Redes de Barramento de Campo",
		"Geometria N\u00e3o Euclidiana",
		"Engenharia Solar T\u00e9rmica",
		"Fundamentos de Eletr\u00f4nica",
		"Mec\u00e2nica Estat\u00edstica",
		"Tecnologia de Elast\u00f4meros",
		"Transfer\u00eancia de Calor II",
		"Mec\u00e2nica Qu\u00e2ntica II",
		"Processamento de Cer\u00e2micas",
		"Transportes e Mobilidade Urbana",
		"Processamento de Sinais Neurais",
		"Processamento Digital de Sinais",
		"Natureza da Informa\u00e7\u00e3o",
		"Organiza\u00e7\u00e3o de Projeto",
		"Estrutura e Din\u00e2mica Social",
		"Engenharia \u00d3ptica e Imagens",
		"Sistemas Multi-Rob\u00f4s Sociais",
		"Evolu\u00e7\u00e3o da F\u00ecsica",
		"Computa\u00e7\u00e3o Gr\u00e1fica",
		"Filosofia do Ensino de Filosofia",
		"Informa\u00e7\u00e3o e Sociedade",
		"Fen\u00f4menos Ondulat\u00f3rios",
		"De Mercosul, Unasul \u00e0 Celac",
		"Morfofisiologia animal comparada",
		"Fundamentos da Eletrost\u00e1tica",
		"C\u00e1lculo Vetorial e Tensorial",
		"Desenho e Projeto em Qu\u00edmica",
		"Gest\u00e3o da Inova\u00e7\u00e3o",
		"Fundamentos da Relatividade Geral",
		"Semin\u00e1rios em Qu\u00edmica I",
		"Neurobiologia Molecular e Celular",
		"Nanoci\u00eancia e Nanotecnologia",
		"Teorias Contempor\u00e2neas de RI",
		"Fontes Renov\u00e1veis de Energia",
		"Biologia Molecular e Biotecnologia",
		"Fundamentos da Eletrodin\u00e2mica",
		"Eletr\u00f4nica de Pot\u00eancia I",
		"Direito Internacional P\u00fablico",
		"Processamento de Linguagem Natural",
		"Desenvolvimento e Sustentabilidade",
		"Semin\u00e1rios em Qu\u00edmica II",
		"Gest\u00e3o de Opera\u00e7\u00f5es",
		"Gera\u00e7\u00e3o Distribu\u00edda",
		"Interpreta\u00e7\u00f5es do Brasil",
		"Teoria das Distribui\u00e7\u00f5es",
		"Engenharia de Reservat\u00f3rios I",
		"Instala\u00e7\u00f5es Hospitalares",
		"Engenharia de Perfura\u00e7\u00e3o",
		"Hist\u00f3ria Econ\u00f4mica Geral",
		"Planejamento e Pol\u00edtica Rural",
		"Algoritmos e Estruturas de Dados II",
		"Polui\u00e7\u00e3o Atmosf\u00e9rica",
		"Laborat\u00f3rio de F\u00edsica III",
		"Cidadania, Direitos e Desigualdades",
		"Energia, Meio Ambiente e Sociedade",
		"Pr\u00e1ticas de Qu\u00edmica Verde",
		"Estabilidade e Controle de Aeronaves",
		"Bases Computacionais da Ci\u00eancia",
		"Energia, Sociedade e Desenvolvimento",
		"Intera\u00e7\u00e3o Fluido-Estrutura",
		"Direito Ambiental e Urban\u00edstico",
		"Pol\u00edticas de Educa\u00e7\u00e3o",
		"Tecnologia do V\u00e1cuo e Criogenia",
		"Introdu\u00e7\u00e3o \u00e0 Economia",
		"\u00c1lgebra Linear Avan\u00e7ada II",
		"Opera\u00e7\u00f5es Unit\u00e1rias I",
		"M\u00e9todos de Otimiza\u00e7\u00e3o",
		"F\u00edsica de Reatores Nucleares I",
		"Pr\u00e1ticas em Qu\u00edmica Verde",
		"Mec\u00e2nica dos Fluidos Viscosos",
		"Planejamento Urbano e Metropolitano",
		"Hist\u00f3ria da Educa\u00e7\u00e3o",
		"Engenharia de Sistemas E\u00f3licos",
		"Patrim\u00f4nio Cultural e Paisagem",
		"Controle Avan\u00e7ado de Rob\u00f4s",
		"L\u00f3gicas N\u00e3o Cl\u00e1ssicas",
		"Desenvolvimento Integrado do Produto",
		"Engenharia de Biocombust\u00edveis I",
		"Engenharia de Sistemas Fotovoltaicos",
		"Ci\u00eancia, Tecnologia e Sociedade",
		"Estado e Rela\u00e7\u00f5es de Poder",
		"\u00c9tica e Responsabilidade Social",
		"Computadores, \u00c9tica e Sociedade",
		"Forma\u00e7\u00e3o de Grupos Sociais",
		"Engenharia de Recursos H\u00eddricos",
		"Teoria Axiom\u00e1tica dos Conjuntos",
		"Fen\u00f4menos Eletromagn\u00e9ticos",
		"T\u00e9cnicas Modernas em Fototerapia",
		"Qu\u00edmica de Coordena\u00e7\u00e3o",
		"Opera\u00e7\u00f5es Unit\u00e1rias II",
		"Gest\u00e3o de Custos Avan\u00e7ada 1",
		"Biocombust\u00edveis e biorrefinarias",
		"Rob\u00f4s M\u00f3veis Aut\u00f4nomos",
		"F\u00edsico-Qu\u00edmica Experimental",
		"Pr\u00e1tica de Ensino de Filosofia I",
		"Siderurgia e Engenharia dos A\u00e7os",
		"Temas da Filosofia Contempor\u00e2nea",
		"An\u00e1lise Qu\u00edmica Instrumental",
		"Fun\u00e7\u00f5es de Uma Vari\u00e1vel",
		"Hist\u00f3ria da Ci\u00eancia e Ensino",
		"Regula\u00e7\u00e3o Ambiental e Urbana",
		"Planejamento e Pol\u00edtica Ambiental",
		"Laborat\u00f3rio de F\u00edsica Moderna",
		"Eletr\u00f4nica Anal\u00f3gica Aplicada",
		"Circuitos El\u00e9tricos e Fot\u00f4nica",
		"T\u00f3picos Experimentais em Materiais I",
		"Radia\u00e7\u00f5es Eletromagn\u00e9ticas",
		"Laborat\u00f3rio de Sistemas Operacionais",
		"Hist\u00f3ria das Ci\u00eancias no Brasil",
		"Transforma\u00e7\u00f5es Bioqu\u00edmicas",
		"Introdu\u00e7\u00e3o ao Estudo do Direito",
		"Teoria do Planejamento Urbano e Ambiental",
		"Gerenciamento e Interoperabilidade de Redes",
		"Filosofia da Ci\u00eancia P\u00f3s-kuhniana",
		"\u00c9tica: perspectivas contempor\u00e2neas",
		"Gest\u00e3o Estrat\u00e9gica e Organizacional",
		"Hist\u00f3ria das Id\u00e9ias Biol\u00f3gicas",
		"Planejamento e Controle de Produ\u00e7\u00e3o",
		"Circuitos Hidr\u00e1ulicos e Pneum\u00e1ticos",
		"Teoria da Informa\u00e7\u00e3o e C\u00f3digos",
		"Mecanismos de Rea\u00e7\u00f5es Org\u00e2nicas",
		"Est\u00e9tica: Perspectivas Contempor\u00e2neas",
		"Equa\u00e7\u00f5es Diferenciais Ordin\u00e1rias",
		"Transporte de Petr\u00f3leo e G\u00e1s Natural",
		"Modelos e Ferramentas de Gest\u00e3o Ambiental",
		"Educa\u00e7\u00e3o em sa\u00fade e sexualidade",
		"Otimiza\u00e7\u00e3o em Projetos de Estruturas",
		"T\u00e9cnicas Modernas em Fotodiagn\u00f3stico",
		"T\u00f3picos de Hist\u00f3ria da Ci\u00eancia",
		"T\u00f3picos em F\u00edsica Contempor\u00e2nea",
		"Pr\u00e1ticas de Ensino de Matem\u00e1tica II",
		"Laborat\u00f3rio de F\u00edsica B\u00e1sica I",
		"Intelig\u00eancia Artificial em Rob\u00f3tica",
		"Introdu\u00e7\u00e3o \u00e0 Astron\u00e1utica",
		"Princ\u00edpios de Mec\u00e2nica Qu\u00e2ntica",
		"Projeto de Elementos Estruturais de Aeronaves I",
		"Caracteriza\u00e7\u00e3o de Matrizes Ambientais",
		"Pesquisa e Comunica\u00e7\u00e3o Cient\u00edfica",
		"Instrumenta\u00e7\u00e3o e Metrologia \u00d3ptica",
		"Evolu\u00e7\u00e3o dos Conceitos Matem\u00e1ticos",
		"Bases Epistemol\u00f3gicas da Ci\u00eancia Moderna",
		"Engenharia de Reabilita\u00e7\u00e3o e Biofeedback",
		"Cidades, Globaliza\u00e7\u00e3o e Projetos Urbanos",
		"Legisla\u00e7\u00e3o Relacionada \u00e0 Sa\u00fade",
		"An\u00e1lise e Controle de Sistemas Mec\u00e2nicos",
		"Introdu\u00e7\u00e3o \u00e0 An\u00e1lise Funcional",
		"Centrais Termoel\u00e9tricas e Cogera\u00e7\u00e3o",
		"Confiabilidade Industrial em Sistemas de Gest\u00e3o",
		"Fun\u00e7\u00f5es e Rea\u00e7\u00f5es Org\u00e2nicas",
		"Teoria do Conhecimento: Empirismo versus Racionalismo",
		"Sem\u00e2ntica de Linguagens de Programa\u00e7\u00e3o",
		"Problemas Metodol\u00f3gicos das Ci\u00eancias Sociais",
		"Regula\u00e7\u00e3o e Mercado de Energia El\u00e9trica",
		"Inicia\u00e7\u00e3o \u00e0 Pesquisa Cient\u00edfica II",
		"Processamento e An\u00e1lise de Sinais Biom\u00e9dicos",
		"Trajet\u00f3rias das Pol\u00edticas de C.T.I no Brasil",
		"T\u00f3picos Especiais em Engenharia Ambiental e Urbana",
		"Din\u00e2mica e Desafios dos Processos Migrat\u00f3rios",
		"Oficina de Planejamento e Governan\u00e7a Metropolitana",
		"Din\u00e2mica dos Investimentos Produtivos Internacionais",
		"An\u00e1lise da Conjuntura Internacional Contempor\u00e2nea",
		"Propriedades El\u00e9tricas, Magn\u00e9ticas e \u00d3pticas",
		"Modelos de Comunica\u00e7\u00e3o nas Organiza\u00e7\u00f5es",
		"Forma\u00e7\u00e3o das Pol\u00edticas Educacionais no Brasil",
		"An\u00e1lise de Redes de Transporte e Distribui\u00e7\u00e3o",
		"Jogos Digitais: Aspectos T\u00e9cnicos e Aplica\u00e7\u00f5es",
		"Qu\u00edmica Anal\u00edtica e Bioanal\u00edtica Avan\u00e7ada",
		"Materiais Comp\u00f3sitos e Aplica\u00e7\u00f5es Estruturais",
		"Eletroanal\u00edtica e T\u00e9cnicas de Separa\u00e7\u00e3o",
		"Metodologia de Pesquisa em Rela\u00e7\u00f5es Internacionais",
		"Educa\u00e7\u00e3o \u00e0 Dist\u00e2ncia e Novas Tecnologias",
		"Supervis\u00e3o e Monitoramento de Processos Energ\u00e9ticos",
		"M\u00e9todos Quantitativos para Planejamento Estrat\u00e9gico",
		"Pensamento Cr\u00edtico das Rela\u00e7\u00f5es Internacionais",
		"Pensamento Marxista e seus Desdobramentos Contempor\u00e2neos",
		"Pensamento Kantiano e seus Desdobramentos Contempor\u00e2neos",
		"Opera\u00e7\u00e3o de Sistemas El\u00e9tricos de Pot\u00eancia",
		"Processamento de Informa\u00e7\u00e3o em L\u00ednguas Naturais",
		"Engenharia Econ\u00f4mica Aplicada a Sistemas de Gest\u00e3o",
		"Teoria e Gest\u00e3o de Organiza\u00e7\u00f5es P\u00fablicas",
		"Princ\u00edpios de \u00c9tica em Servi\u00e7os de Sa\u00fade",
		"Hist\u00f3ria da Filosofia Moderna: o Idealismo alem\u00e3o",         // surf, uh!
		"Inicia\u00e7\u00e3o \u00e0 Pesquisa Cient\u00edfica III",
		"Espectroscopia \u00d3ptica em Sistemas Biol\u00f3gicos",
		"Contamina\u00e7\u00e3o e Remedia\u00e7\u00e3o de Solos",
		"Gest\u00e3o de Recursos Energ\u00e9ticos e Ambientais",
		"Introdu\u00e7\u00e3o a Materiais Biocompat\u00edveis",
		"Pr\u00e1ticas de Ci\u00eancias no Ensino Fundamental",
		"Engenharia de Tecidos e \u00d3rg\u00e3os Artificiais",
		"Estat\u00edstica Aplicada a Sistemas de Gest\u00e3o",
		"Introdu\u00e7\u00e3o \u00e0 F\u00edsica M\u00e9dica",
		"T\u00f3picos Especiais em Engenharia Organizacional",
		"Programa\u00e7\u00e3o para Dispositivos M\u00f3veis",
		"Introdu\u00e7\u00e3o aos Sistemas de Propuls\u00e3o",
		"Hist\u00f3ria das Rela\u00e7\u00f5es Internacionais",
		"Pensamento Latino-Americano e Pol\u00edticas de CTI",
		"Transforma\u00e7\u00f5es nos Seres Vivos e Ambiente",
		"Inova\u00e7\u00e3o nos Servi\u00e7os P\u00fablicos",
		"Observat\u00f3rio de Pol\u00edticas P\u00fablicas",
		"Introdu\u00e7\u00e3o \u00e0 Psicolingu\u00edstica",
		"Desenvolvimento Econ\u00f4mico e Social no Brasil",
		"Opera\u00e7\u00f5es e Equipamentos Industriais II",
		"Hidrog\u00eanio e C\u00e9lulas a Combust\u00edvel",
		"T\u00e9cnicas de An\u00e1lise Estrutural e Projeto",
		"Engenharia Aplicada a Sistemas Biol\u00f3gicos II",
		"Problemas Metaf\u00edsicos: Perspectivas Modernas",
		"Introdu\u00e7\u00e3o \u00e0 Bioinform\u00e1tica",
		"Introdu\u00e7\u00e3o \u00e0 F\u00edsica Nuclear",
		"Processamento e Conforma\u00e7\u00e3o de Metais",
		"Economia do Petr\u00f3leo e do G\u00e1s Natural",
		"Ci\u00eancias dos Materiais Biocompat\u00edveis",
		"Economia Pol\u00edtica Internacional da Energia",
		"Quest\u00f5es Atuais no Ensino de Ci\u00eancias",
		"Neuroci\u00eancia da Cogni\u00e7\u00e3o Musical",
		"Arte, Ci\u00eancia, Tecnologia e Pol\u00edtica",
		"Introdu\u00e7\u00e3o ao Direito Administrativo",
		"Experimenta\u00e7\u00e3o e Ensino de Qu\u00edmica",
		"Materiais para Tecnologia da Informa\u00e7\u00e3o",
		"Empreendedorismo e Desenvolvimento de Neg\u00f3cios",
		"Introdu\u00e7\u00e3o \u00e0s Curvas Alg\u00e9bricas",
		"Din\u00e2mica e Controle de Ve\u00edculos Espaciais",
		"Introdu\u00e7\u00e3o \u00e0 Administra\u00e7\u00e3o",
		"Trabalho de Conclus\u00e3o de Curso em Qu\u00edmica",
		"Trabalho de Conclus\u00e3o de Curso em F\u00edsica",
		"Geotecnia Aplicada ao Planejamento Urbano-Ambiental",
		"Nascimento e Desenvolvimento da Ci\u00eancia Moderna",
		"Poder e Cultura na Sociedade da Informa\u00e7\u00e3o",
		"Introdu\u00e7\u00e3o \u00e0 Engenharia Biom\u00e9dica",
		"Tend\u00eancias em Educa\u00e7\u00e3o Matem\u00e1tica",
		"Inicia\u00e7\u00e3o \u00e0 Pesquisa Cient\u00edfica I",
		"Or\u00e7amento e Pol\u00edtica Or\u00e7ament\u00e1ria",
		"Pr\u00e1tica Avan\u00e7ada de Programa\u00e7\u00e3o A",
		"Instrumenta\u00e7\u00e3o Biom\u00e9dica Avan\u00e7ada",
		"Fun\u00e7\u00f5es Complexas e Transformadas Integrais",
		"Banco de Dados de Apoio \u00e0 Tomada de Decis\u00e3o",
		"Est\u00e1gio Supervisionado em Computa\u00e7\u00e3o I",
		"M\u00e9todos Quantitativos para Ci\u00eancias Sociais",
		"Pr\u00e1tica Avan\u00e7ada de Programa\u00e7\u00e3o C",
		"Pr\u00e1tica Avan\u00e7ada de Programa\u00e7\u00e3o B",
		"Processamento e An\u00e1lise de Falhas em Biomateriais",
		"Fundamentos de Convers\u00e3o de Energia El\u00e9trica",
		"Processos Industriais Org\u00e2nicos e Inorg\u00e2nicos",
		"Educa\u00e7\u00e3o Cient\u00edfica, Sociedade e Cultura",
		"T\u00e9cnicas Aplicadas a Processos Biotecnol\u00f3gicos",
		"Ger\u00eancia de Ativos Tang\u00edveis e Intang\u00edveis",
		"Aplica\u00e7\u00f5es de Elementos Finitos para Engenharia",
		"Introdu\u00e7\u00e3o \u00e0s Pol\u00edticas P\u00fablicas",
		"Administra\u00e7\u00e3o Municipal e Desenvolvimento Local",
		"Projeto de Microdispositivos para Instrumenta\u00e7\u00e3o",
		"Laborat\u00f3rio de Propriedades F\u00edsicas de Materiais",
		"Governo, Burocracia e Administra\u00e7\u00e3o P\u00fablica",
		"Teoria do conhecimento: a epistemologia contempor\u00e2nea",
		"Introdu\u00e7\u00e3o \u00e0 Engenharia do Petr\u00f3leo II",
		"Introdu\u00e7\u00e3o \u00e0 Programa\u00e7\u00e3o de Jogos",
		"Modelagem e Simula\u00e7\u00e3o de Sistemas Biom\u00e9dicos",
		"Problemas Metaf\u00edsicos: Perspectivas Contempor\u00e2neas",
		"Universo das Institui\u00e7\u00f5es Pol\u00edticas no Brasil",
		"Pol\u00edtica Internacional dos EUA e da Uni\u00e3o Europeia",
		"Introdu\u00e7\u00e3o \u00e0 Infer\u00eancia Estat\u00edstica",
		"Transfer\u00eancia de Calor Aplicada a Sistemas Aeroespaciais",
		"Hist\u00f3ria da Filosofia Antiga: Plat\u00e3o e o Platonismo",
		"An\u00e1lise de S\u00e9ries Temporais - T\u00f3picos Especiais",
		"Pensamento Hegeliano e seus Desdobramentos Contempor\u00e2neos",
		"Introdu\u00e7\u00e3o \u00e0 Engenharia de Biocombust\u00edveis",
		"Cartografia e Geoprocessamento para o Planejamento Territorial",
		"Evolu\u00e7\u00e3o e Diversifica\u00e7\u00e3o da Vida na Terra",
		"Hist\u00f3ria da Filosofia Moderna: perspectivas racionalistas",
		"Forma\u00e7\u00e3o Hist\u00f3rica do Brasil Contempor\u00e2neo",
		"Hist\u00f3ria da Filosofia Contempor\u00e2nea: o S\u00e9culo XX",
		"Processos Termoqu\u00edmicos de Convers\u00e3o Energ\u00e9tica",
		"Prote\u00e7\u00e3o de Sistemas El\u00e9tricos de Pot\u00eancia",
		"Automa\u00e7\u00e3o de Sistemas El\u00e9tricos de Pot\u00eancia",
		"Institui\u00e7\u00f5es Judiciais e Pol\u00edticas P\u00fablicas",
		"Finan\u00e7as, Gest\u00e3o e Administra\u00e7\u00e3o Financeira",
		"Introdu\u00e7\u00e3o \u00e0s Humanidades e Ci\u00eancias Sociais",
		"Hist\u00f3ria da Filosofia Contempor\u00e2nea: o s\u00e9culo XIX",
		"Pensamento Nietzcheano e seus Desdobramentos Contempor\u00e2neos",
		"Hist\u00f3ria e An\u00e1lise da Pol\u00edtica Externa Brasileira",
		"Biodiversidade: Intera\u00e7\u00f5es entre organismos e ambiente",
		"Trabalho de Conclus\u00e3o de Curso de Planejamento Territorial I",
		"Sistema Financeiro Internacional: de Bretton Woods ao non-sistema",
		"Introdu\u00e7\u00e3o \u00e0 Modelagem e Processos Estoc\u00e1sticos",
		"Avalia\u00e7\u00e3o e Monitoramento de Pol\u00edticas P\u00fablicas",
		"Engenharia Econ\u00f4mica Aplicada \u00e0 Engenharia de Gest\u00e3o",
		"Estado e Desenvolvimento Econ\u00f4mico no Brasil Contempor\u00e2neo",
		"Trabalho de Conclus\u00e3o de Curso de Pol\u00edticas P\u00fablicas I",
		"Modelos Econ\u00f4micos e An\u00e1lise das Din\u00e2micas Territoriais",
		"Pol\u00edticas P\u00fablicas de G\u00eanero, Etnia e Gera\u00e7\u00e3o",
		"Introdu\u00e7\u00e3o \u00e0 F\u00edsica de Part\u00edculas Elementares",
		"Trabalho de Conclus\u00e3o de Curso de Pol\u00edticas P\u00fablicas II",
		"Hist\u00f3ria da Filosofia Medieval: Patr\u00edstica e Escol\u00e1stica",
		"Oficina de Planejamento de \u00c1reas Periurbanas, Interioranas e Rurais",
		"Trajet\u00f3ria da OPEP e da Ag\u00eancia Internacional de Energia (IEA)",
		"M\u00e9todos de Elementos Finitos Aplicados a Sistemas Biom\u00e9dicos",
		"Globaliza\u00e7\u00e3o e os Processos de Integra\u00e7\u00e3o Regional",
		"Hist\u00f3ria da Filosofia Moderna: o Iluminismo e seus desdobramentos",
		"Regula\u00e7\u00e3o e Ag\u00eancias Reguladoras no Contexto Brasileiro",
		"Tranfer\u00eancia de Calor e Mec\u00e2nica dos Fluidos Computacional II",
		"Filosofia da Ci\u00eancia: em torno \u00e0 concep\u00e7\u00e3o ortodoxa",
		"Regime Internacional dos Direitos Humanos e a Estrat\u00e9gia Brasileira",
		"Perspectiva de An\u00e1lise do Estado e das Pol\u00edticas P\u00fablicas",
		"An\u00e1lise Est\u00e1tica em Sistemas El\u00e9tricos de Pot\u00eancia",
		"Efeitos Biol\u00f3gicos das Radia\u00e7\u00f5es N\u00e3o Ionizantes",
		"Introdu\u00e7\u00e3o \u00e0 Probabilidade e \u00e0 Estat\u00edstica",
		"Arranjos Institucionais e Marco Regulat\u00f3rio do Territ\u00f3rio",
		"Elabora\u00e7\u00e3o, An\u00e1lise e Avalia\u00e7\u00e3o de Projetos",
		"Pol\u00edmeros S\u00edntese Caracteriza\u00e7\u00e3o e Processos",
		"M\u00e9todos Matem\u00e1ticos Aplicados a Sistemas Biom\u00e9dicos",
		"Instrumenta\u00e7\u00e3o e Sensores em Ve\u00edculos Aeroespaciais",
		"Negocia\u00e7\u00e3o e Solu\u00e7\u00e3o de Conflitos Organizacionais",
		"Conhecimento na Economia: Abordagens e Interfaces com as Atividades de CT&I",
		"Regime Internacional dos Direitos Humanos e a Atua\u00e7\u00e3o Brasileira",
		"Eletrifica\u00e7\u00e3o Rural com Recursos Energ\u00e9ticos Renov\u00e1veis",
		"Pol\u00edticas P\u00fablicas de Interven\u00e7\u00e3o Territorial no Brasil",
		"Conflitos no Ciberespa\u00e7o: Ativismo e Guerra nas Redes Cibern\u00e9ticas",
		"Governan\u00e7a P\u00fablica, Democracia e Pol\u00edticas no Territ\u00f3rio",
		"Impacto Ambiental e Social na Cadeia  de Produ\u00e7\u00e3o de Petr\u00f3leo",
		"Pr\u00e1ticas de Ensino de Ci\u00eancias e Matem\u00e1tica no Ensino Fundamental",
		"Gest\u00e3o da Qualidade, Seguran\u00e7a, Sa\u00fade e Ambiental Aplicada em Projetos",
		"An\u00e1lise da Produ\u00e7\u00e3o do Espa\u00e7o e Pol\u00edticas P\u00fablicas Urbanas",
		"M\u00e9todos e T\u00e9cnicas de An\u00e1lise de Informa\u00e7\u00e3o para o Planejamento",
		"Mudan\u00e7a Tecnol\u00f3gica e Din\u00e2mica Capitalista na Economia Contempor\u00e2nea",
		"Regimes de Negocia\u00e7\u00e3o Financeira Internacional e a Estrat\u00e9gia Brasileira",
		"Seguran\u00e7a Internacional em Perspectiva Hist\u00f3rica e Desafios Contempor\u00e2neos",
		"Regimes de Negocia\u00e7\u00e3o Ambiental Internacional e a Estrat\u00e9gia Brasileira",
		"Sistemas Integrados de Gest\u00e3o da Qualidade Ambiental, Seguran\u00e7a e Sa\u00fade",
		"Hist\u00f3ria de Atua\u00e7\u00e3o do Brasil nos Processos de Integra\u00e7\u00e3o Sul-americana",
		"Negocia\u00e7\u00f5es Internacionais, Propriedade Intelectual e Transfer\u00eancia Tecnol\u00f3gica",
		"T\u00f3picos de Otimiza\u00e7\u00e3o em Sistemas El\u00e9tricos de Pot\u00eancia e Aplica\u00e7\u00f5es",
		"Consolida\u00e7\u00e3o de Conceitos e M\u00e9todos de Fen\u00f4menos Eletromagn\u00e9ticos",
		"T\u00e9cnicas de Tomadas de Decis\u00e3o Aplic\u00e1veis em Modelos de Interdepend\u00eancia",
		"Mem\u00f3ria, Identidades Sociais e Cidadania nas Sociedades Complexas Contempor\u00e2neas",
		"T\u00e9cnicas de Tomadas de Decis\u00e3o Aplic\u00e1veis em Modelos de Depend\u00eancia",
		"Projeto e Desenvolvimento de Sistemas para An\u00e1lise de Dados M\u00e9dicos",
		"Mobiliza\u00e7\u00e3o Produtiva dos Territ\u00f3rios e Desenvolvimento Local",
		"Introdu\u00e7\u00e3o \u00e0s Equa\u00e7\u00f5es Diferenciais Ordin\u00e1rias",
		"Servo-Sistema para Rob\u00f4s e Acionamento para Sistemas Mecatr\u00f4nicos",
		"Trajet\u00f3ria Internacional do Continente Africano e do Oriente M\u00e9dio",
		"Introdu\u00e7\u00e3o \u00e0 Qu\u00edmica Verde e Qu\u00edmica Sustent\u00e1vel",
		"Trajet\u00f3ria de Desenvolvimento de Pa\u00edses Exportadores de Petr\u00f3leo",
		"Bioqu\u00edmica: estrutura, propriedade e fun\u00e7\u00f5es de Biomol\u00e9culas",
		"Introdu\u00e7\u00e3o aos Processos de Fabrica\u00e7\u00e3o Metal - Mec\u00e2nico",
		"Introdu\u00e7\u00e3o ao Processamento de Sinais de Voz, \u00c1udio e Ac\u00fasticos",
		"Administra\u00e7\u00e3o P\u00fablica e Reforma do Estado em Perspectiva Comparada",
		"Engenharia de Sistemas de Comunica\u00e7\u00e3o e Miss\u00e3o Cr\u00edtica",
		"Introdu\u00e7\u00e3o \u00e0 Biofot\u00f4nica e \u00d3ptica Biom\u00e9dica",
		"Hist\u00f3ria da Filosofia Antiga: Arist\u00f3teles e o Aristotelismo",
		"Filosofia da Ci\u00eancia: o debate Popper-Kuhn e seus desdobramentos",
		"Instrumenta\u00e7\u00e3o para o ensino de Ci\u00eancias e Biologia",
		"Pr\u00e1ticas de Ensino de Matem\u00e1tica no Ensino Fundamental",
		"T\u00e9cnicas Avan\u00e7adas de Gest\u00e3o da Produ\u00e7\u00e3o",
		"Introdu\u00e7\u00e3o aos Sistemas El\u00e9tricos de Pot\u00eancia",
		"Blendas Polim\u00e9ricas e Aditiva\u00e7\u00e3o de Pol\u00edmeros",
		"Introdu\u00e7\u00e3o a Processos Industriais Biotecnol\u00f3gicos",
		"Trabalho de Conclus\u00e3o de Curso em Matem\u00e1tica III",
		"Rela\u00e7\u00f5es Internacionais e Globaliza\u00e7\u00e3o",
		"M\u00e9todos de An\u00e1lise em Qu\u00edmica Org\u00e2nica",
		"Laborat\u00f3rio de Guiagem, Navega\u00e7\u00e3o e Controle",
		"Introdu\u00e7\u00e3o \u00e0 Neuroci\u00eancia Computacional",
		"Princ\u00edpios e Aplica\u00e7\u00f5es de Biomec\u00e2nica",
		"Introdu\u00e7\u00e3o aos Processos de Fabrica\u00e7\u00e3o",
		"Cultura, Identidade e Pol\u00edtica na Am\u00e9rica Latina",
		"Processadores Digitais em Controle e Automa\u00e7\u00e3o",
		"Estrat\u00e9gias de Comunica\u00e7\u00e3o Organizacional",
		"M\u00e9todos Computacionais para An\u00e1lise Estrutural",
		"Redes de Distribui\u00e7\u00e3o de Energia El\u00e9trica",
		"Simula\u00e7\u00e3o de Sistemas de Comunica\u00e7\u00e3o",
		"M\u00e9todos de Pesquisa em Pol\u00edticas P\u00fablicas",
		"Geometria Plana e Constru\u00e7\u00f5es Geom\u00e9tricas",
		"T\u00f3picos Avan\u00e7ados em Qu\u00edmica Org\u00e2nica",
		"Desenvolvimento e Degenera\u00e7\u00e3o do Sistema Nervoso",
		"Filosofia Pol\u00edtica: perspectivas contempor\u00e2neas",
		"Trajet\u00f3rias das Pol\u00edticas de C, T & I no Brasil",
		"Introdu\u00e7\u00e3o \u00e0 Engenharia do Petr\u00f3leo I",
		"Trabalho de Conclus\u00e3o de Curso em Matem\u00e1tica II",
		"Economia Pol\u00edtica da Seguran\u00e7a Alimentar Global",
		"Planejamento Estrat\u00e9gico em Gest\u00e3o de Projetos",
		"An\u00e1lise Econ\u00f4mica de Projetos Energ\u00e9ticos",
		"Trabalho de Conclus\u00e3o de Curso em Matem\u00e1tica I",
		"Forma\u00e7\u00e3o Hist\u00f3rica da Am\u00e9rica Latina",
		"Simula\u00e7\u00e3o e Processamento de Pol\u00edmeros",
		"Inform\u00e1tica Aplicada ao Planejamento Territorial",
		"Historiografia e Hist\u00f3ria das Ci\u00eancias",
		"Engenharia Aplicada a Sistemas Biol\u00f3gicos I",
		"Intera\u00e7\u00f5es At\u00f4micas e Moleculares",
		"An\u00e1lise de Sistemas Din\u00e2micos Lineares",
		"Hist\u00f3ria da Filosofia da Antiguidade Tardia",
		"Termodin\u00e2mica Estat\u00edstica de Materiais",
		"Sistemas de Tratamento de \u00c1guas e Efluentes",
		"Seguran\u00e7a de Instala\u00e7\u00f5es Nucleares",
		"Regula\u00e7\u00e3o Urban\u00edstica e Ambiental",
		"Aten\u00e7\u00e3o e Estados de Consci\u00eancia",
		"Filosofia da Natureza, Mecanicismo e Cosmologia",
		"Opera\u00e7\u00f5es e Equipamentos Industriais I",
		"Fun\u00e7\u00f5es de V\u00e1rias Vari\u00e1veis",
		"Trabalho de Conclus\u00e3o de Curso em Biologia",
		"Eletroqu\u00edmica e Cin\u00e9tica Qu\u00edmica",
		"Introdu\u00e7\u00e3o \u00e0 Filosofia da Mente",
		"Introdu\u00e7\u00e3o ao Direito Constitucional",
		"Surgimento da China como Pot\u00eancia Mundial",
		"Progressos e M\u00e9todos em Neuroci\u00eancia",
		"Planejamento e Controle da Produ\u00e7\u00e3o",
		"Sistema ONU e os Desafios do Multilateralismo",
		"Introdu\u00e7\u00e3o \u00e0 Neuroci\u00eancia",
		"Termo-Hidr\u00e1ulica de Reatores Nucleares I",
		"Tecnologia de Produ\u00e7\u00e3o de Biodiesel",
		"An\u00e1lise de Sistemas e Modelagem Ambiental",
		"Arquitetura de Computadores de Alto Desempenho",
		"Pr\u00e1ticas de Ensino de Matem\u00e1tica III",
		"Laborat\u00f3rio de F\u00edsica B\u00e1sica II",
		"Introdu\u00e7\u00e3o \u00e0 Engenharia Nuclear",
		"Simula\u00e7\u00e3o de Modelos de Gest\u00e3o",
		"Evolu\u00e7\u00e3o e Diversidade de Plantas I",
		"Automa\u00e7\u00e3o em Sistemas de Manufatura",
		"Finan\u00e7as II (Apre\u00e7amento de Ativos)",
		"Engenharia de Gest\u00e3o - Vis\u00e3o Geral",
		"Filosofia no Brasil e na Am\u00e9rica Latina",
		"Propriedades Mec\u00e2nicas e T\u00e9rmicas",
		"Pol\u00edticas P\u00fablicas Sul-Americanas",
		"M\u00e9todos da Mec\u00e2nica Qu\u00e2ntica",
		"No\u00e7\u00f5es de Astronomia e Cosmologia",
		"Automa\u00e7\u00e3o de Sistemas Industriais",
		"Fundamentos de Economia e Sociologia Urbana",
		"Transformadas em Sinais e Sistemas Lineares",
		"Pr\u00e1ticas de Ensino de Qu\u00edmica III",
		"Qu\u00edmica Anal\u00edtica Cl\u00e1ssica I",
		"Laborat\u00f3rio de F\u00edsica M\u00e9dica",
		"Fenomenologia e Filosofia Hermen\u00eautica",
		"Habita\u00e7\u00e3o e Assentamentos Humanos",
		"Indicadores de Pol\u00edticas P\u00fablicas",
		"Forma\u00e7\u00e3o Hist\u00f3rica do Brasil",
		"Avalia\u00e7\u00e3o de Impactos Ambientais",
		"M\u00e9todos Quantitativos de An\u00e1lise",
		"Fontes N\u00e3o-Renov\u00e1veis de Energia",
		"Federalismo e Pol\u00edticas P\u00fablicas",
		"Teoria Cr\u00edtica e Escola de Frankfurt",
		"Mec\u00e2nica Qu\u00e2ntica Avan\u00e7ada",
		"Fundamentos da Mec\u00e2nica dos Fluidos",
		"Sensa\u00e7\u00e3o e Percep\u00e7\u00e3o",
		"Elementos Finitos Aplicados em Materiais",
		"T\u00f3picos Computacionais em Materiais",
		"Introdu\u00e7\u00e3o \u00e0 Criptografia",
		"Confiabilidade de Componentes e Sistemas",
		"Desenvolvimento Humano e Pobreza Urbana",
		"Teoria da Medida e Integra\u00e7\u00e3o",
		"Conserva\u00e7\u00e3o da Biodiversidade",
		"Caracteriza\u00e7\u00e3o de Materiais",
]

var input = document.getElementById('in')
var menu = document.getElementById("autocomplete")
var title = document.getElementById('title')
var tree = new Trie()





window.onload = function(){
    for(var i=0;i<a.length;i++)
        tree.inserir(a[i])
    input.value = ''
    input.onkeyup = autocomplete
}


function mostralista(prefixo){
    var lista = tree.listar(prefixo)

	for(var i=0;i<lista.length;i++){
	    li = document.createElement('li')
	    li.nome = lista[i]
	    li.innerHTML = (i+1) + " " + lista[i]
	    li.onclick = function(){
	        title.innerHTML = ":" + this.nome
	    }
	    menu.appendChild(li)
	}
}



 /* * * * * * * * *
 * Class Trie, uh! *
  * * * * * * * * */

function Trie(){
    return{
        root: {letra:[], fim:false, n:0},
        out: [],
        compare:"",
        ctest:0,

        inserir: function(str){
                var atual = this.root
                for(var i = 0; i < str.length; i++){
                    var k = str.charCodeAt(i)
                    if(!atual.letra[k])
                        atual.letra[k] = {letra:[], fim:false}
                    atual = atual.letra[k]
                }
                atual.fim = true
	        },



        listar: function(compare){
            this.compare = compare
            this.out = []
            this.listarRec(this.root, "")
            return this.out
        },


        listarRec: function(node, str){

            if(str.length > this.compare.length){

                test = true
                for(var i = 0; i < this.compare.length; i++){
                    if(str.charAt(str.length-this.compare.length+i).toUpperCase() != this.compare.charAt(i).toUpperCase())
                        test = false
                }


                if(test)
                    this.inOrder(node, str)
                    //this.out.push(str)
            }

            for(var i=0; i < 256; i++)
                if(node.letra[i])
                    this.listarRec(node.letra[i], str + String.fromCharCode(i))

        },

        inOrder: function(node, str){
            if(node.fim)
                this.out.push(str)

                for(var i=0; i < 256; i++)
                    if(node.letra[i])
                        this.inOrder(node.letra[i], str + String.fromCharCode(i))
        }
    }
}

function autocomplete(){
    clear()
    var prefixo = input.value
    if(prefixo!="") mostralista(prefixo)
}

function clear(){
    while(menu.hasChildNodes())
	    menu.removeChild(menu.firstChild)
}



// estudar isto: http://stackoverflow.com/questions/35066881/autocomplete-using-a-trie-in-java


